-- Cloudflare D1 Schema for Yewon Rules

CREATE TABLE "Category" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "depth" INTEGER NOT NULL DEFAULT 1,
  "sortOrder" INTEGER NOT NULL DEFAULT 1,
  "parentId" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("parentId") REFERENCES "Category" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Department" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "code" TEXT UNIQUE,
  "sortOrder" INTEGER NOT NULL DEFAULT 1,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Rule" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "ruleNumber" TEXT NOT NULL UNIQUE,
  "initialSound" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'EFFECTIVE',
  "categoryId" TEXT NOT NULL,
  "departmentId" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("categoryId") REFERENCES "Category" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("departmentId") REFERENCES "Department" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "Revision" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "ruleId" TEXT NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 1,
  "versionName" TEXT NOT NULL,
  "revisionType" TEXT NOT NULL DEFAULT 'AMENDMENT',
  "enactmentDate" DATETIME NOT NULL,
  "effectiveDate" DATETIME NOT NULL,
  "announcementNumber" TEXT NOT NULL,
  "description" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ruleId") REFERENCES "Rule" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "Revision_ruleId_version_key" ON "Revision"("ruleId", "version");

CREATE TABLE "Article" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "revisionId" TEXT NOT NULL,
  "chapter" TEXT,
  "section" TEXT,
  "articleNumber" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "contentJson" TEXT NOT NULL,
  "contentHtml" TEXT,
  "contentText" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 1,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("revisionId") REFERENCES "Revision" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "ArticleComparison" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "revisionId" TEXT NOT NULL,
  "beforeArticleId" TEXT,
  "afterArticleId" TEXT,
  "note" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("revisionId") REFERENCES "Revision" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("beforeArticleId") REFERENCES "Article" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY ("afterArticleId") REFERENCES "Article" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE "Attachment" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "ruleId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "fileUrl" TEXT NOT NULL,
  "fileSize" INTEGER,
  "fileType" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("ruleId") REFERENCES "Rule" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Notice" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "dept" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_Article_revisionId" ON "Article"("revisionId");
CREATE INDEX IF NOT EXISTS "idx_Revision_ruleId" ON "Revision"("ruleId");
CREATE INDEX IF NOT EXISTS "idx_Rule_categoryId" ON "Rule"("categoryId");
CREATE INDEX IF NOT EXISTS "idx_Rule_departmentId" ON "Rule"("departmentId");
CREATE INDEX IF NOT EXISTS "idx_Attachment_ruleId" ON "Attachment"("ruleId");
CREATE INDEX IF NOT EXISTS "idx_ArticleComparison_revisionId" ON "ArticleComparison"("revisionId");
 
CREATE TABLE " "Opinion ( 
  id TEXT NOT NULL PRIMARY KEY, 
  title TEXT NOT NULL, 
  content TEXT NOT NULL, 
  author TEXT NOT NULL, 
  password TEXT NOT NULL, 
  attachmentUrl TEXT, 
  attachmentName TEXT, 
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP 
);
