name = "yewon-rules"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "yewon-rules-db"
database_id = "f448ab63-128a-4e09-a1e1-02095e73d92e"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "yewon-rules-storage"
